# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iitBombayfosse.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CSV_Editor(object):
    def setupUi(self, CSV_Editor):
        CSV_Editor.setObjectName("CSV_Editor")
        CSV_Editor.resize(520, 430)
        self.centralwidget = QtWidgets.QWidget(CSV_Editor)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 501, 391))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setGeometry(QtCore.QRect(0, 1, 491, 361))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget1 = (self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(9, -1, 481, 361))
        self.widget1.setObjectName("widget1")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_2 = plot_figure(self.tab_3)
        self.widget_2.setGeometry(QtCore.QRect(0, -1, 491, 361))
        self.widget_2.setObjectName("widget_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_3 = plot_figure(self.tab_4)
        self.widget_3.setGeometry(QtCore.QRect(0, -1, 491, 361))
        self.widget_3.setObjectName("widget_3")
        self.tabWidget.addTab(self.tab_4, "")
        CSV_Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CSV_Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuPlot = QtWidgets.QMenu(self.menubar)
        self.menuPlot.setObjectName("menuPlot")
        CSV_Editor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CSV_Editor)
        self.statusbar.setObjectName("statusbar")
        CSV_Editor.setStatusBar(self.statusbar)
        self.actionedit_data = QtWidgets.QAction(CSV_Editor)
        self.actionedit_data.setObjectName("actionedit_data")
        self.actionSave = QtWidgets.QAction(CSV_Editor)
        self.actionSave.setObjectName("actionSave")
        self.actionAddData = QtWidgets.QAction(CSV_Editor)
        self.actionAddData.setObjectName("actionAddData")
        self.actionQuit = QtWidgets.QAction(CSV_Editor)
        self.actionQuit.setObjectName("actionQuit")
        self.actionEditData = QtWidgets.QAction(CSV_Editor)
        self.actionEditData.setCheckable(True)
        self.actionEditData.setChecked(True)
        self.actionEditData.setObjectName("actionEditData")
        self.actionScatterPlot = QtWidgets.QAction(CSV_Editor)
        self.actionScatterPlot.setObjectName("actionScatterPlot")
        self.actionScatterWithLinePlot = QtWidgets.QAction(CSV_Editor)
        self.actionScatterWithLinePlot.setObjectName("actionScatterWithLinePlot")
        self.actionLinePlot = QtWidgets.QAction(CSV_Editor)
        self.actionLinePlot.setObjectName("actionLinePlot")
        self.actionSave_Plot = QtWidgets.QAction(CSV_Editor)
        self.actionSave_Plot.setObjectName("actionSave_Plot")
        self.menufile.addAction(self.actionedit_data)
        self.menufile.addAction(self.actionSave)
        self.menufile.addAction(self.actionAddData)
        self.menufile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionEditData)
        self.menuPlot.addAction(self.actionScatterPlot)
        self.menuPlot.addAction(self.actionScatterWithLinePlot)
        self.menuPlot.addAction(self.actionLinePlot)
        self.menuPlot.addAction(self.actionSave_Plot)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(CSV_Editor)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(CSV_Editor)

    def retranslateUi(self, CSV_Editor):
        _translate = QtCore.QCoreApplication.translate
        CSV_Editor.setWindowTitle(_translate("CSV_Editor", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("CSV_Editor", "CSV_Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CSV_Editor", "ScatterPlot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("CSV_Editor", "ScatterwithLinePlot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("CSV_Editor", "LinePlot"))
        self.menufile.setTitle(_translate("CSV_Editor", "File"))
        self.menuEdit.setTitle(_translate("CSV_Editor", "Edit"))
        self.menuPlot.setTitle(_translate("CSV_Editor", "Plot"))
        self.actionedit_data.setText(_translate("CSV_Editor", "LoadCSV"))
        self.actionSave.setText(_translate("CSV_Editor", "SaveCSV"))
        self.actionAddData.setText(_translate("CSV_Editor", "AddData"))
        self.actionQuit.setText(_translate("CSV_Editor", "Quit"))
        self.actionEditData.setText(_translate("CSV_Editor", "EditData"))
        self.actionScatterPlot.setText(_translate("CSV_Editor", "ScatterPlot"))
        self.actionScatterWithLinePlot.setText(_translate("CSV_Editor", "ScatterWithLinePlot"))
        self.actionLinePlot.setText(_translate("CSV_Editor", "LinePlot"))
        self.actionSave_Plot.setText(_translate("CSV_Editor", "Save Plot"))

from plot_figure import plot_figure
